
after-all::
	-ln -sf CGIJSONObject.framework/Headers CGIJSONObject
	-ln -sf CGIJSONObject.framework/libFusionKit.so libCGIJSONObject.so

before-clean::
	-rm CGIJSONObject
	-rm libCGIJSONObject.so

	
