include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME := CGIHello

CGIHello_OBJC_FILES := CGITestApplicationDelegate.m
CGIHello_C_FILES := main.c
CGIHello_VERSION := 5.0

-include GNUmakefile.preamble

include $(GNUSTEP_MAKEFILES)/tool.make

-include GNUmakefile.postamble
